package com.example.webshop.dto;

import lombok.Data;

@Data
public class CustomerInfoDto {
    // private Long id;            // Optional, for existing customers
    private String name;
    private String email;
    private String address;     // customer address if applicable

    // getters and setters are generated by Lombok
    public String getName() {
        return name;    
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return address; 
    }
    public void setAddress(String address) {
        this.address = address;
    }
}



