package com.example.webshop.dto;

import lombok.Data;
import java.util.List;
import com.example.webshop.dto.CustomerInfoDto;

@Data
public class OrderRequestDto {
    private CustomerInfoDto customer;       // Customer info for order
    private List<OrderItemDto> items; 
    
    // getters and setters are generated by Lombok
    public CustomerInfoDto getCustomer() {
        return customer;
    }
    public void setCustomer(CustomerInfoDto customer) {
        this.customer = customer;
    }
    public List<OrderItemDto> getItems() {
        return items;
    }
    public void setItems(List<OrderItemDto> items) {
        this.items = items;
    }
    
}