package com.example.webshop.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Entity
@Table(name = "order_items")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class OrderItemEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private Long productId;

    @Column(nullable = false)
    private Integer quantity;

    @Column(nullable = false)
    private BigDecimal price;

    @Column(name = "price_at_purchase", nullable = false)
    private BigDecimal priceAtPurchase;

    
}










// package com.example.webshop.entity;

// import jakarta.persistence.*;
// import lombok.AllArgsConstructor;
// import lombok.Data;
// import lombok.NoArgsConstructor;
// import com.example.webshop.model.OrderEntity;

// import java.math.BigDecimal;

// @Entity
// @Table(name = "order_items")
// @Data
// @NoArgsConstructor
// @AllArgsConstructor
// public class OrderItem {

//     @Id
//     @GeneratedValue(strategy = GenerationType.IDENTITY)
//     private Long id;

//     // Product ID
//     @Column(nullable = false)
//     private Long productId;

//     // Quantity of the product
//     @Column(nullable = false)
//     private Integer quantity;

//     // Current price (optional if needed for display/reporting)
//     @Column(nullable = false)
//     private BigDecimal price;

//     // Price at the time of order (used for total calculations)
//     @Column(name = "price_at_purchase", nullable = false)
//     private BigDecimal priceAtPurchase;

// }









// package com.example.webshop.entity;

// import jakarta.persistence.*;
// import lombok.*;

// import java.math.BigDecimal;

// @Entity
// @Data
// @NoArgsConstructor
// @AllArgsConstructor
// @Builder
// public class OrderItem {

//     @Id
//     @GeneratedValue(strategy = GenerationType.IDENTITY)
//     private Long id;

//     private Long productId;

//     private Integer quantity;

//     private BigDecimal priceAtPurchase;

//     @ManyToOne
//     @JoinColumn(name = "order_id")
//     private OrderEntity order;
// }









// package com.example.webshop.entity;

// import jakarta.persistence.*;
// import lombok.AllArgsConstructor;
// import lombok.Data;
// import lombok.NoArgsConstructor;

// import java.math.BigDecimal;

// @Entity
// @Table(name = "order_items")
// @Data
// @NoArgsConstructor
// @AllArgsConstructor
// public class OrderItem {

//     @Id
//     @GeneratedValue(strategy = GenerationType.IDENTITY)
//     private Long id;
//     private Long productId;
//     private String productName;
//     private Integer quantity;
//     private BigDecimal price;
//     private BigDecimal priceAtPurchase;

//     // Getter and Setter methods are generated by Lombok's @Data annotation

//     public OrderItem(Long productId, String productName, Integer quantity, BigDecimal priceAtPurchase) {
//         this.productId = productId;
//         this.productName = productName;
//         this.quantity = quantity;
//         this.price = BigDecimal.ZERO; // Default price, can be set later
//         this.priceAtPurchase = priceAtPurchase;
//     }
// }










// package com.example.webshop.entity;

// import java.math.BigDecimal;
// import jakarta.persistence.*;
// import lombok.AllArgsConstructor;
// import lombok.Data;
// import lombok.NoArgsConstructor;

// @Data
// @NoArgsConstructor
// @AllArgsConstructor
// @Entity(name = "OrderItemEntity")
// public class OrderItem {

//     @Id
//     @GeneratedValue(strategy = GenerationType.IDENTITY)
//     private Long id;
//     private Long productId;
//     private Integer quantity;
//     private BigDecimal price;
//     private BigDecimal priceAtPurchase;

//     // Custom constructor without ID (for manual creation before persistence)
//     public OrderItem(Long id, Long productId, Integer quantity, BigDecimal priceAtPurchase) {
//         this.id = id; // ID can be null if not yet persisted
//         this.productId = productId;
//         this.quantity = quantity;
//         this.price = BigDecimal.ZERO; // Default price, can be set later
//         this.priceAtPurchase = priceAtPurchase;
//     }

//     // constructor, setters, etc.

//     public Long getId() {
//         return id;
//     }
//     public void setId(Long id) {
//         this.id = id;
//     }
//     public Long getProductId() {
//         return productId;
//     }
//     public void setProductId(Long productId) {
//         this.productId = productId;
//     }
//     public Integer getQuantity() {
//         return quantity;
//     }
//     public void setQuantity(Integer quantity) {
//         this.quantity = quantity;
//     }
//     public BigDecimal getPriceAtPurchase() {
//         return priceAtPurchase;
//     }
//     public void setPriceAtPurchase(BigDecimal priceAtPurchase) {
//         this.priceAtPurchase = priceAtPurchase;
//     }

//     public BigDecimal getPrice() {
//         return price;
//     }
//     public void setPrice(BigDecimal price) {
//         this.price = price;
//     }
//     // Getter for price, if needed

    

//     // Optional: convenience constructor with default price
//     public OrderItem(Long productId, Integer quantity) {
//         this.productId = productId;
//         this.quantity = quantity;
//         this.priceAtPurchase = BigDecimal.ZERO;
//     }
// }









// package com.example.webshop.entity;

// import java.math.BigDecimal;
// import jakarta.persistence.*;
// import lombok.AllArgsConstructor;
// import lombok.Data;
// import lombok.NoArgsConstructor;

// @Data
// @NoArgsConstructor
// @AllArgsConstructor
// @Entity(name = "OrderItemEntity")
// public class OrderItem {

//     @Id
//     @GeneratedValue(strategy = GenerationType.IDENTITY)
//     private Long id;

//     private Long productId;
//     private Integer quantity;
//     private BigDecimal priceAtPurchase;


//     public OrderItem(Long productId, Integer quantity, BigDecimal priceAtPurchase) {
//         this.productId = productId;
//         this.quantity = quantity;
//         this.priceAtPurchase = priceAtPurchase;
//     }

//     // getters and setters
//     public Long getId() {
//         return id;
//     }
//     public void setId(Long id) {
//         this.id = id;
//     }
//     public Long getProductId() {
//         return productId;
//     }
//     public void setProductId(Long productId) {
//         this.productId = productId;
//     }
//     public Integer getQuantity() {
//         return quantity;
//     }
//     public void setQuantity(Integer quantity) {
//         this.quantity = quantity;
//     }
//     public BigDecimal getPriceAtPurchase() {
//         return priceAtPurchase;
//     }
//     public void setPriceAtPurchase(BigDecimal priceAtPurchase) {
//         this.priceAtPurchase = priceAtPurchase;
//     }
//     @Override
//     public String toString() {
//         return "OrderItem{" +
//                 "id=" + id +
//                 ", productId=" + productId +
//                 ", quantity=" + quantity +
//                 ", priceAtPurchase=" + priceAtPurchase +
//                 '}';
//     }
//     @Override
//     public boolean equals(Object o) {
//         if (this == o) return true;
//         if (!(o instanceof OrderItem)) return false;
//         OrderItem orderItem = (OrderItem) o;
//         return id != null && id.equals(orderItem.id);
//     }
//     @Override
//     public int hashCode() {
//         return 31;
//     }

//     @Id
//     @GeneratedValue(strategy = GenerationType.IDENTITY)
//     private Long id;  // ✅ REQUIRED for @Entity

//     private Long productId;
//     private Integer quantity;
//     private BigDecimal priceAtPurchase;

//     public OrderItem(Long productId, Integer quantity, BigDecimal priceAtPurchase) {
//         this.productId = productId;
//         this.quantity = quantity;
//         this.priceAtPurchase = priceAtPurchase;
//     }

//     public OrderItem(Long productId, Integer quantity) {
//         this.productId = productId;
//         this.quantity = quantity;
//         this.priceAtPurchase = BigDecimal.ZERO;      
//     }
// }










// package com.example.webshop.entity;

// import java.math.BigDecimal;

// import jakarta.persistence.Entity;
// import jakarta.persistence.Id;
// import jakarta.persistence.GeneratedValue;
// import jakarta.persistence.GenerationType;
// import jakarta.persistence.*;


// import lombok.AllArgsConstructor;
// import lombok.Data;
// import lombok.NoArgsConstructor;

// // @Entity
// @Data
// @NoArgsConstructor
// @AllArgsConstructor
// @Entity(name = "OrderItemEntity")
// public class OrderItem {
//     @Id
//     @GeneratedValue(strategy = GenerationType.IDENTITY)
//     // private Long id;

//     private Long productId;
//     private Integer quantity;
//     private BigDecimal priceAtPurchase;

//     // Getters and Setters
//     public Long getId() {
//         return id;
//     }
//     public void setId(Long id) {
//         this.id = id;
//     }
//     public Long getProductId() {
//         return productId;
//     }
//     public void setProductId(Long productId) {
//         this.productId = productId;
//     }
//     public Integer getQuantity() {
//         return quantity;
//     }
//     public void setQuantity(Integer quantity) {
//         this.quantity = quantity;
//     }
//     public BigDecimal getPriceAtPurchase() {
//         return priceAtPurchase;
//     }
//     public void setPriceAtPurchase(BigDecimal priceAtPurchase) {
//         this.priceAtPurchase = priceAtPurchase;
//     }
//     @Override
//     public String toString() {
//         return "OrderItem{" +
//                 "id=" + id +
//                 ", productId=" + productId +
//                 ", quantity=" + quantity +
//                 ", priceAtPurchase=" + priceAtPurchase +
//                 '}';
//     }
//     @Override
//     public boolean equals(Object o) {
//         if (this == o) return true;
//         if (!(o instanceof OrderItem)) return false;
//         OrderItem orderItem = (OrderItem) o;
//         return id != null && id.equals(orderItem.id);
//     }
//     @Override
//     public int hashCode() {
//         return 31;
//     }
//     public OrderItem(Long productId, Integer quantity, BigDecimal priceAtPurchase) {
//         this.productId = productId;
//         this.quantity = quantity;
//         this.priceAtPurchase = priceAtPurchase;
//     }
//     public OrderItem(Long id, Long productId, Integer quantity, BigDecimal priceAtPurchase) {
//         this.id = id;
//         this.productId = productId;
//         this.quantity = quantity;
//         this.priceAtPurchase = priceAtPurchase;
//     }
//     public OrderItem(Long productId, Integer quantity) {
//         this.productId = productId;
//         this.quantity = quantity;
//         this.priceAtPurchase = BigDecimal.ZERO; // Default value, can be set later      
//     }
    
// }